@url = http://localhost:3000/api/v1/auth
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJ1c2VybmFtZSI6InJpY2hpZSIsInBhc3N3b3JkIjoiJDJiJDEwJE1nRkpvWkliMlI0b1NlRXBQblFTS3VxQnU1STlPeEdvUmkyZDhVWGdHMkw5djhpVUJFemVpIiwicm9sZSI6ImFkbWluIiwibmFtZSI6IlJpY2hpZSIsImNyZWF0ZWRBdCI6IjIwMjEtMTEtMjlUMDY6MzE6MzguNTg4WiIsInVwZGF0ZWRBdCI6IjIwMjEtMTEtMjlUMDY6MzE6MzguNTg4WiJ9LCJpYXQiOjE2Mzg2MTgyODUsImV4cCI6MTYzODYyMTg4NX0.W2zt6t2GQTjxmKN5tmSrBifGn5gp4ABuDy_GFJcj4_4 

### Login
POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "username" : "richie",
    "password" : "richie"
}

### Me
GET {{url}}/me HTTP/1.1
Authorization: {{token}}

### logout
DELETE {{url}}/logout HTTP/1.1
Authorization: {{token}}