@baseUrl= {{url}}/{{version}}

###ANCHOR  Auth

### Login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "username" : "richie",
    "password" : "richie"
}

### Me
GET {{baseUrl}}/auth/me HTTP/1.1
Authorization: {{token}}

### logout
DELETE {{baseUrl}}/auth/logout HTTP/1.1
Authorization: {{token}}

###ANCHOR Petugas 

### 
GET {{baseUrl}}/petugas HTTP/1.1
Authorization: {{token}}

###
GET {{baseUrl}}/petugas/admin HTTP/1.1
Authorization: {{token}}

###
PUT  {{baseUrl}}/petugas/pengaduan/6/proses HTTP/1.1
Authorization: {{token}}

###ANCHOR Pengaduan

### Get all pengaduan based on client ip
GET {{baseUrl}}/pengaduan HTTP/1.1

### post
POST {{baseUrl}}/pengaduan HTTP/1.1
Content-Type: application/json

{
    "isiLaporan" : "Help me, My Dog Is Dying!!"
}