@url = http://localhost:3000/api/v1/user
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJ1c2VybmFtZSI6InJpY2hpZSIsInBhc3N3b3JkIjoiJDJiJDEwJE1nRkpvWkliMlI0b1NlRXBQblFTS3VxQnU1STlPeEdvUmkyZDhVWGdHMkw5djhpVUJFemVpIiwicm9sZSI6ImFkbWluIiwibmFtZSI6IlJpY2hpZSIsImNyZWF0ZWRBdCI6IjIwMjEtMTEtMjlUMDY6MzE6MzguNTg4WiIsInVwZGF0ZWRBdCI6IjIwMjEtMTEtMjlUMDY6MzE6MzguNTg4WiJ9LCJpYXQiOjE2Mzg0NTM2NzUsImV4cCI6MTYzODQ1NzI3NX0.z26viNMmIuk8-se9O7W30hNrFYWvLRnlCbXPKCkIq0M

GET {{url}} HTTP/1.1
Authorization: {{token}}

###

GET {{url}}/admin HTTP/1.1
Authorization: {{token}}

###

GET {{url}}/op HTTP/1.1
Authorization: {{token}}